# Generated by Django 4.2 on 2023-04-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('waitingapproval', 'Waiting approval'), ('active', 'Active'), ('draft', 'Draft'), ('deleted', 'Deleted')], default='active', max_length=50),
        ),
    ]
