# Generated by Django 4.2 on 2023-04-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('draft', 'Draft'), ('active', 'Active'), ('waitingapproval', 'Waiting approval')], default='active', max_length=50),
        ),
    ]
