# Generated by Django 4.2 on 2023-04-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_thumbnail_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deleted', 'Deleted'), ('waitingapproval', 'Waiting approval')], default='active', max_length=50),
        ),
    ]
