# Generated by Django 4.2 on 2023-04-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('waitingapproval', 'Waiting approval'), ('active', 'Active'), ('deleted', 'Deleted'), ('draft', 'Draft')], default='active', max_length=50),
        ),
    ]
