# Generated by Django 4.2 on 2023-04-29 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(default='some string', on_delete=django.db.models.deletion.CASCADE, related_name='brand_category', to='store.category'),
        ),
        migrations.AddField(
            model_name='size',
            name='brand',
            field=models.ForeignKey(default='some string', on_delete=django.db.models.deletion.CASCADE, related_name='size_brand', to='store.brand'),
        ),
        migrations.AddField(
            model_name='size',
            name='category',
            field=models.ForeignKey(default='some string', on_delete=django.db.models.deletion.CASCADE, related_name='size_category', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('active', 'Active'), ('draft', 'Draft'), ('waitingapproval', 'Waiting approval')], default='active', max_length=50),
        ),
    ]
