# Generated by Django 4.2 on 2023-04-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('waitingapproval', 'Waiting approval'), ('deleted', 'Deleted'), ('draft', 'Draft')], default='active', max_length=50),
        ),
    ]
