# Generated by Django 4.2 on 2023-04-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_product_status_delete_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deleted', 'Deleted'), ('waitingapproval', 'Waiting approval')], default='active', max_length=50),
        ),
    ]
